name: Show Me the S3cr3tz

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write secrets to file
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          VPS_API_PATH: ${{ secrets.VPS_API_PATH }}
          VPS_FRONT_PATH: ${{ secrets.VPS_FRONT_PATH }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          set -euo pipefail
          {
            echo "DATABASE_URL=$DATABASE_URL"
            echo "JWT_SECRET=$JWT_SECRET"
            echo "NODE_ENV=$NODE_ENV"
            echo "VPS_API_PATH=$VPS_API_PATH"
            echo "VPS_FRONT_PATH=$VPS_FRONT_PATH"
            echo "VPS_HOST=$VPS_HOST"
            echo "VPS_PATH=$VPS_PATH"
            echo "VPS_SSH_KEY=$VPS_SSH_KEY"
            echo "VPS_USER=$VPS_USER"
          } > secrets.txt
          # Also provide base64 form if your terminal breaks on special chars
          base64 secrets.txt > secrets.txt.b64

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true


